TT-442 mypage view 작성
twenty-three-23/peech-flutter pull request #235
Opened 2024-09-30 08:54 UTC by snacktime81

2024-10-11 08:30 UTC, Seungman-dev requested changes

2024-10-11 08:30 UTC, Seungman-dev commented on lib/features/mypage/controller/mypage_controller.dart
throw 에서 gotoStore라고 되어있는데 gotoStore는 앱스토어 실행하는곳에서 사용한거라 [gotoStrore] 가 아니라 [launchUrl] 로 수정해주시면 감사하겠습니다~!

2024-10-11 09:01 UTC, snacktime81 commented on lib/features/mypage/controller/mypage_controller.dart
수정했습니다. 그리고 회원탈퇴도 연동했습니다.

2024-10-12 05:24 UTC, Seungman-dev approved these changes
확인했습니다. 문제 없어 보입니다. 회원탈퇴 버튼 눌렀을 때 확인 팝업을 띄워주면 좋을 것 같은데, 그부분은 제가 바텀 네비게이션에 연결하면서 추가하겠습니다.

2024-10-12 06:03 UTC, merged